// <auto-generated />
namespace dashboard_mvc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class lcgms_and_team_links : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(lcgms_and_team_links));
        
        string IMigrationMetadata.Id
        {
            get { return "201601192013516_lcgms_and_team_links"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
